cp ../array_class.cpp array_class.cpp
cp ../array_objects.cpp array_objects.cpp
cp ../class_eg.cpp class_eg.cpp
cp ../complex_num.cpp complex_num.cpp
cp ../complex_overload.cpp complex_overload.cpp
cp ../constructor_derived.cpp constructor_derived.cpp
cp ../constructors.cpp constructors.cpp
cp ../conversion.cpp conversion.cpp
cp ../copy_constructor.cpp copy_constructor.cpp
cp ../default_arg.cpp default_arg.cpp
cp ../destructor.cpp destructor.cpp
cp ../dynamic_constructor.cpp dynamic_constructor.cpp
cp ../dynamic_object.cpp dynamic_object.cpp
cp ../dynamic.cpp dynamic.cpp
cp ../friend_reference.cpp friend_reference.cpp
cp ../friend.cpp friend.cpp
cp ../friend_class.cpp friend_class.cpp
cp ../hybrid_inheritance.cpp hybrid_inheritance.cpp
cp ../initialization_list.cpp initialization_list.cpp
cp ../inline.cpp inline.cpp
cp ../manipulator.cpp manipulator.cpp
cp ../matrix.cpp matrix.cpp
cp ../minus_overloading.cpp minus_overloading.cpp
cp ../multilevel.cpp multilevel.cpp
cp ../multiple.cpp multiple.cpp
cp ../operator_friend.cpp operator_friend.cpp
cp ../person.cpp person.cpp
cp ../plus_overload.cpp plus_overload.cpp
cp ../private_inheritance.cpp private_inheritance.cpp
cp ../public_inheritance.cpp public_inheritance.cpp
cp ../rectangle.cpp rectangle.cpp
cp ../reference.cpp reference.cpp
cp ../scope_reso.cpp scope_reso.cpp
cp ../virtual.cpp virtual.cpp